# Site settings
title: "Maksim Kudryavtsev"
description: "Hey, I'm Max, Tech Lead with a 6+ years of experience in creating software products. I specialize in web development and team management. Not just built but grew up 3 teams and 4 products. I implemented Agile-processes, got rid of familiar thing in favor of convenient ones, led software architecture &mdash; all of above helped to speed up delivery and reduced costs."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Maksim Kudryavtsev"
resume_title:                   "Technical leader"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "maxsior@ya.ru"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "address • phone • email"
display_header_contact_info:    "false"

resume_header_intro: "<p>Tech Lead with a 6+ years of experience in creating software products. I specialize in web development and team management. Not just built but grew up 3 teams and 4 products. I implemented Agile-processes, got rid of familiar thing in favor of convenient ones, led software architecture &mdash; all of above helped to speed up delivery and reduced costs.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Maxsior"
  # resume_twitter_url:           "http://twitter.com/"
  # resume_dribbble_url:          "https://dribbble.com/"
  # resume_facebook_url:          "https://facebook.com/"
  resume_linkedin_url:          "https://www.linkedin.com/in/maksim-kudryavtsev-967152274/"
  resume_instagram_url:         "https://www.instagram.com/maxsi0r/"
  resume_website_url:           "https://maxsior.ru"
  # resume_medium_url:            "https://medium.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
